// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "screens/ui_Screen_1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

// Rust FFI declarations
extern void rust_set_bright(uint8_t state);
extern void rust_set_relax(uint8_t state);
extern void rust_toggle_bright(void);
extern void rust_toggle_relax(void);

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen_1);
}

void ui_destroy(void)
{
    ui_Screen_1_screen_destroy();
}

// FFI Functions - called by Rust backend
// These update the UI elements when data changes

void ui_update_water_level_async(int level)
{
    // This function is called from Rust threads (non-LVGL thread)
    // Use lv_async_call to safely update UI from main thread
    printf("[UI] Async water level update received: %d%%\n", level);
    ui_set_water_level(level);
}

void ui_set_water_level(int level)
{
    // This function should be called from LVGL thread only
    // Updates the water level display
    printf("[UI] Updating water level display: %d%%\n", level);
    
    // Clamp level to 0-100
    if (level < 0) level = 0;
    if (level > 100) level = 100;
    
    // Update the arc value
    if (ui_WaterTankArc != NULL) {
        lv_arc_set_value(ui_WaterTankArc, level);
    }
    
    // Update the label text
    if (ui_WaterLevel != NULL) {
        char buf[8];
        snprintf(buf, sizeof(buf), "%d", level);
        lv_label_set_text(ui_WaterLevel, buf);
    }
    
    // Change arc color based on level
    if (ui_WaterTankArc != NULL) {
        if (level < 10) {
            // Critical - red
            lv_obj_set_style_arc_color(ui_WaterTankArc, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
        } else if (level < 20) {
            // Low - orange
            lv_obj_set_style_arc_color(ui_WaterTankArc, lv_color_hex(0xFFA500), LV_PART_INDICATOR | LV_STATE_DEFAULT);
        } else {
            // Normal - blue
            lv_obj_set_style_arc_color(ui_WaterTankArc, lv_color_hex(0x1F84D8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
        }
    }
}

void ui_set_bright_state(int state)
{
    // Updates bright switch state from Rust/backend
    printf("[UI] Setting bright state: %d\n", state);
    if (ui_BrightSwitch != NULL) {
        if (state) {
            lv_obj_add_state(ui_BrightSwitch, LV_STATE_CHECKED);
        } else {
            lv_obj_clear_state(ui_BrightSwitch, LV_STATE_CHECKED);
        }
    }
}

void ui_set_relax_state(int state)
{
    // Updates relax switch state from Rust/backend
    printf("[UI] Setting relax state: %d\n", state);
    if (ui_RelaxSwitch != NULL) {
        if (state) {
            lv_obj_add_state(ui_RelaxSwitch, LV_STATE_CHECKED);
        } else {
            lv_obj_clear_state(ui_RelaxSwitch, LV_STATE_CHECKED);
        }
    }
}
