// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include <stdio.h>
#include "ui.h"
#include "ui_helpers.h"

// Thread-safe water level update - called from Rust thread
typedef struct {
    int level;
} water_level_data_t;

static water_level_data_t pending_water_level = { -1 };

// LVGL async callback - runs on main LVGL thread
static void apply_water_level_update(void *data)
{
    int level = *(int*)data;
    
    if(ui_WaterTankArc != NULL && level >= 0 && level <= 100) {
        lv_arc_set_value(ui_WaterTankArc, level);
    }
    if(ui_WaterLevel != NULL) {
        char buf[8];
        lv_snprintf(buf, sizeof(buf), "%d", level);
        lv_label_set_text(ui_WaterLevel, buf);
    }
    printf("[UI] Water level updated to: %d%%\n", level);
}

// Called by Rust from any thread - schedules async update
void ui_update_water_level_async(int level)
{
    pending_water_level.level = level;
    lv_async_call(apply_water_level_update, &pending_water_level.level);
}

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen_1);
}

void ui_destroy(void)
{
    ui_Screen_1_screen_destroy();
}

// ==================== RUST INTEGRATION ====================
// These functions are called by Rust to update the UI display

void ui_set_water_level(int level)
{
    if(ui_WaterTankArc != NULL && level >= 0 && level <= 100) {
        lv_arc_set_value(ui_WaterTankArc, level);
        printf("[UI] Water arc updated to: %d%%\n", level);
    }
    if(ui_WaterLevel != NULL) {
        char buf[8];
        lv_snprintf(buf, sizeof(buf), "%d", level);
        lv_label_set_text(ui_WaterLevel, buf);
        printf("[UI] Water label updated to: %d%%\n", level);
    }
}

void ui_set_bright_state(int state)
{
    if(ui_brightButton != NULL) {
        if(state) {
            lv_obj_add_state(ui_brightButton, LV_STATE_CHECKED);
            printf("[UI] Bright button state: ON\n");
        } else {
            lv_obj_clear_state(ui_brightButton, LV_STATE_CHECKED);
            printf("[UI] Bright button state: OFF\n");
        }
    }
}

void ui_set_relax_state(int state)
{
    if(ui_relaxButton != NULL) {
        if(state) {
            lv_obj_add_state(ui_relaxButton, LV_STATE_CHECKED);
            printf("[UI] Relax button state: ON\n");
        } else {
            lv_obj_clear_state(ui_relaxButton, LV_STATE_CHECKED);
            printf("[UI] Relax button state: OFF\n");
        }
    }
}
