// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen_1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_129797224);    // assets/resized-off-light.png
LV_IMG_DECLARE(ui_img_404674758);    // assets/resized-on-light.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

// RUST FFI FUNCTIONS - Called by C UI, implemented in Rust
extern void rust_backend_init(void);
extern void rust_set_bright(int state);
extern void rust_set_relax(int state);
extern int rust_get_bright(void);
extern int rust_get_relax(void);
extern int rust_toggle_bright(void);
extern int rust_toggle_relax(void);
extern int rust_get_water_level(void);
extern void rust_set_water_level(int level);
extern int rust_is_water_low(void);
extern int rust_is_water_critical(void);

// C UI UPDATE FUNCTIONS - Called by Rust to update display
// NOTE: These must be called from LVGL thread only!
extern void ui_set_water_level(int level);
extern void ui_set_bright_state(int state);
extern void ui_set_relax_state(int state);

// Thread-safe async update - can be called from any thread
extern void ui_update_water_level_async(int level);

// UI UPDATE CALLBACK - Register this in Rust to receive state updates
// This callback is called by Rust backend when state changes via MQTT
// Parameters: water_level (0-100), bright_state (0/1), relax_state (0/1)
extern void ui_update_callback(int water_level, int bright_state, int relax_state);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
