// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_Bright;
lv_obj_t * uic_BrightButtonPanel;
lv_obj_t * uic_WaterLevel;
lv_obj_t * uic_WaterTankArc;
lv_obj_t * uic_LightContainer;
lv_obj_t * uic_ArcContainer;
lv_obj_t * uic_Screen_1;
lv_obj_t * ui_Screen_1 = NULL;
lv_obj_t * ui_ArcContainer = NULL;
lv_obj_t * ui_LightContainer = NULL;
lv_obj_t * ui_WaterTankArc = NULL;
lv_obj_t * ui_LightsText = NULL;
lv_obj_t * ui_LightsText2 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_WaterLevel = NULL;
lv_obj_t * ui_BrightButtonPanel = NULL;
lv_obj_t * ui_Bright = NULL;
lv_obj_t * ui_RelaxButtonPanel = NULL;
lv_obj_t * ui_Relax = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Panel7 = NULL;
// event funtions
void ui_event_Bright(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_state_modify(ui_Relax, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Relax(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_state_modify(ui_Bright, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

// build funtions

void ui_Screen_1_screen_init(void)
{
    ui_Screen_1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_1, lv_color_hex(0x0B0B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcContainer = lv_obj_create(ui_Screen_1);
    lv_obj_remove_style_all(ui_ArcContainer);
    lv_obj_set_width(ui_ArcContainer, 455);
    lv_obj_set_height(ui_ArcContainer, 219);
    lv_obj_set_x(ui_ArcContainer, -2);
    lv_obj_set_y(ui_ArcContainer, 119);
    lv_obj_set_align(ui_ArcContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ArcContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcContainer, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ArcContainer, lv_color_hex(0x0087C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ArcContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArcContainer, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightContainer = lv_obj_create(ui_Screen_1);
    lv_obj_remove_style_all(ui_LightContainer);
    lv_obj_set_width(ui_LightContainer, 455);
    lv_obj_set_height(ui_LightContainer, 211);
    lv_obj_set_x(ui_LightContainer, 0);
    lv_obj_set_y(ui_LightContainer, -127);
    lv_obj_set_align(ui_LightContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LightContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LightContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LightContainer, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LightContainer, lv_color_hex(0xF1E144), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LightContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LightContainer, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WaterTankArc = lv_arc_create(ui_Screen_1);
    lv_obj_set_width(ui_WaterTankArc, 618);
    lv_obj_set_height(ui_WaterTankArc, 264);
    lv_obj_set_x(ui_WaterTankArc, 174);
    lv_obj_set_y(ui_WaterTankArc, 219);
    lv_obj_set_align(ui_WaterTankArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_WaterTankArc, 50);
    lv_arc_set_bg_angles(ui_WaterTankArc, 180, 360);
    lv_obj_set_style_radius(ui_WaterTankArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_WaterTankArc, lv_color_hex(0x000008), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_WaterTankArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_WaterTankArc, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_WaterTankArc, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_WaterTankArc, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_WaterTankArc, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WaterTankArc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WaterTankArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_WaterTankArc, lv_color_hex(0x1F84D8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_WaterTankArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_WaterTankArc, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_WaterTankArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WaterTankArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WaterTankArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_WaterTankArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LightsText = lv_textarea_create(ui_Screen_1);
    lv_obj_set_width(ui_LightsText, 238);
    lv_obj_set_height(ui_LightsText, 48);
    lv_obj_set_x(ui_LightsText, -7);
    lv_obj_set_y(ui_LightsText, -198);
    lv_obj_set_align(ui_LightsText, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_LightsText, "Lights mode");
    lv_textarea_set_placeholder_text(ui_LightsText, "Placeholder...");
    lv_obj_set_style_text_color(ui_LightsText, lv_color_hex(0xFFF526), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightsText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LightsText, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LightsText, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LightsText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LightsText, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LightsText, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LightsText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightsText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LightsText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LightsText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightsText2 = lv_textarea_create(ui_Screen_1);
    lv_obj_set_width(ui_LightsText2, 224);
    lv_obj_set_height(ui_LightsText2, 48);
    lv_obj_set_x(ui_LightsText2, -10);
    lv_obj_set_y(ui_LightsText2, 45);
    lv_obj_set_align(ui_LightsText2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_LightsText2, "Water level");
    lv_textarea_set_placeholder_text(ui_LightsText2, "Placeholder...");
    lv_obj_set_style_text_color(ui_LightsText2, lv_color_hex(0x00B6D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightsText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LightsText2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LightsText2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LightsText2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LightsText2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LightsText2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LightsText2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightsText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LightsText2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LightsText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen_1);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 408
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 612
    lv_obj_set_x(ui_Image1, 197);
    lv_obj_set_y(ui_Image1, 482);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_zoom(ui_Image1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen_1);
    lv_obj_set_width(ui_Panel1, 100);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_x(ui_Panel1, -2);
    lv_obj_set_y(ui_Panel1, 189);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WaterLevel = lv_label_create(ui_Screen_1);
    lv_obj_set_width(ui_WaterLevel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WaterLevel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WaterLevel, -2);
    lv_obj_set_y(ui_WaterLevel, 188);
    lv_obj_set_align(ui_WaterLevel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WaterLevel, "50");
    lv_obj_set_style_text_color(ui_WaterLevel, lv_color_hex(0x00C7EF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WaterLevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_WaterLevel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_WaterLevel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WaterLevel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightButtonPanel = lv_obj_create(ui_Screen_1);
    lv_obj_set_width(ui_BrightButtonPanel, 124);
    lv_obj_set_height(ui_BrightButtonPanel, 102);
    lv_obj_set_x(ui_BrightButtonPanel, -136);
    lv_obj_set_y(ui_BrightButtonPanel, -78);
    lv_obj_set_align(ui_BrightButtonPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrightButtonPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BrightButtonPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightButtonPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightButtonPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BrightButtonPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BrightButtonPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bright = lv_imgbtn_create(ui_Screen_1);
    lv_imgbtn_set_src(ui_Bright, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_166333148, NULL);
    lv_imgbtn_set_src(ui_Bright, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_166333148, NULL);
    lv_imgbtn_set_src(ui_Bright, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_353436330, NULL);
    lv_imgbtn_set_src(ui_Bright, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_353436330, NULL);
    lv_obj_set_width(ui_Bright, 338);
    lv_obj_set_height(ui_Bright, 332);
    lv_obj_set_x(ui_Bright, -33);
    lv_obj_set_y(ui_Bright, 22);
    lv_obj_set_align(ui_Bright, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bright, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_transform_zoom(ui_Bright, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Bright, &ui_img_353436330, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_RelaxButtonPanel = lv_obj_create(ui_Screen_1);
    lv_obj_set_width(ui_RelaxButtonPanel, 124);
    lv_obj_set_height(ui_RelaxButtonPanel, 102);
    lv_obj_set_x(ui_RelaxButtonPanel, 139);
    lv_obj_set_y(ui_RelaxButtonPanel, -78);
    lv_obj_set_align(ui_RelaxButtonPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RelaxButtonPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RelaxButtonPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RelaxButtonPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RelaxButtonPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RelaxButtonPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RelaxButtonPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Relax = lv_imgbtn_create(ui_Screen_1);
    lv_imgbtn_set_src(ui_Relax, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_166333148, NULL);
    lv_imgbtn_set_src(ui_Relax, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_166333148, NULL);
    lv_imgbtn_set_src(ui_Relax, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_353436330, NULL);
    lv_imgbtn_set_src(ui_Relax, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_353436330, NULL);
    lv_obj_set_width(ui_Relax, 338);
    lv_obj_set_height(ui_Relax, 332);
    lv_obj_set_x(ui_Relax, 246);
    lv_obj_set_y(ui_Relax, 23);
    lv_obj_set_align(ui_Relax, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Relax, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_transform_zoom(ui_Relax, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Relax, &ui_img_353436330, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel3 = lv_obj_create(ui_Screen_1);
    lv_obj_set_width(ui_Panel3, 100);
    lv_obj_set_height(ui_Panel3, 34);
    lv_obj_set_x(ui_Panel3, -136);
    lv_obj_set_y(ui_Panel3, -151);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen_1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -136);
    lv_obj_set_y(ui_Label4, -153);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Bright");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xF1E144), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen_1);
    lv_obj_set_width(ui_Panel4, 100);
    lv_obj_set_height(ui_Panel4, 34);
    lv_obj_set_x(ui_Panel4, 140);
    lv_obj_set_y(ui_Panel4, -151);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen_1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 140);
    lv_obj_set_y(ui_Label2, -153);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Relax");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xF1E144), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen_1);
    lv_obj_set_width(ui_Panel5, 7);
    lv_obj_set_height(ui_Panel5, 141);
    lv_obj_set_x(ui_Panel5, -1);
    lv_obj_set_y(ui_Panel5, -99);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFEE25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Screen_1);
    lv_obj_set_width(ui_Panel6, 8);
    lv_obj_set_height(ui_Panel6, 175);
    lv_obj_set_x(ui_Panel6, 191);
    lv_obj_set_y(ui_Panel6, 124);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x0087C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Screen_1);
    lv_obj_set_width(ui_Panel7, 8);
    lv_obj_set_height(ui_Panel7, 175);
    lv_obj_set_x(ui_Panel7, -193);
    lv_obj_set_y(ui_Panel7, 124);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x0087C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Bright, ui_event_Bright, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Relax, ui_event_Relax, LV_EVENT_ALL, NULL);
    uic_Screen_1 = ui_Screen_1;
    uic_ArcContainer = ui_ArcContainer;
    uic_LightContainer = ui_LightContainer;
    uic_WaterTankArc = ui_WaterTankArc;
    uic_WaterLevel = ui_WaterLevel;
    uic_BrightButtonPanel = ui_BrightButtonPanel;
    uic_Bright = ui_Bright;

}

void ui_Screen_1_screen_destroy(void)
{
    if(ui_Screen_1) lv_obj_del(ui_Screen_1);

    // NULL screen variables
    uic_Screen_1 = NULL;
    ui_Screen_1 = NULL;
    uic_ArcContainer = NULL;
    ui_ArcContainer = NULL;
    uic_LightContainer = NULL;
    ui_LightContainer = NULL;
    uic_WaterTankArc = NULL;
    ui_WaterTankArc = NULL;
    ui_LightsText = NULL;
    ui_LightsText2 = NULL;
    ui_Image1 = NULL;
    ui_Panel1 = NULL;
    uic_WaterLevel = NULL;
    ui_WaterLevel = NULL;
    uic_BrightButtonPanel = NULL;
    ui_BrightButtonPanel = NULL;
    uic_Bright = NULL;
    ui_Bright = NULL;
    ui_RelaxButtonPanel = NULL;
    ui_Relax = NULL;
    ui_Panel3 = NULL;
    ui_Label4 = NULL;
    ui_Panel4 = NULL;
    ui_Label2 = NULL;
    ui_Panel5 = NULL;
    ui_Panel6 = NULL;
    ui_Panel7 = NULL;

}
