// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN_1_H
#define UI_SCREEN_1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_1
extern void ui_Screen_1_screen_init(void);
extern void ui_Screen_1_screen_destroy(void);
extern lv_obj_t * ui_Screen_1;
extern lv_obj_t * ui_ArcContainer;
extern lv_obj_t * ui_LightContainer;
extern lv_obj_t * ui_WaterTankArc;
extern lv_obj_t * ui_LightsText;
extern lv_obj_t * ui_LightsText2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_WaterLevel;
extern lv_obj_t * ui_BrightButtonPanel;
extern lv_obj_t * ui_RelaxButtonPanel;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_brightButton;
extern lv_obj_t * ui_relaxButton;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen_1;
extern lv_obj_t * uic_ArcContainer;
extern lv_obj_t * uic_LightContainer;
extern lv_obj_t * uic_WaterTankArc;
extern lv_obj_t * uic_WaterLevel;
extern lv_obj_t * uic_BrightButtonPanel;
extern lv_obj_t * uic_relaxButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

